language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  allow_failures:
    - env: CODACY=1 DEFAULT=0

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0
    - php: 7.0
      env: CODACY=1 DEFAULT=0

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - sh -c "if [ '$CODACY' = '1' ]; then composer require --dev codacy/coverage:dev-master; fi"
  - sh -c "if [ '$CODACY' = '1' ]; then mkdir -p build/logs; fi"

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 ./src; fi"
  - sh -c "if [ '$CODACY' = '1' ]; then phpunit --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$CODACY' = '1' ]; then php vendor/bin/codacycoverage clover; fi"

notifications:
  email: false
